name: dart_playground
description: A simple command-line application.
version: 1.0.0
repository: https://github.com/hidenorly/dart_playground

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  ffi: ^2.1.3
  grpc: ^4.0.1
  http: ^1.3.0
  protobuf: ^3.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
